### ISSUE TITLE
Add a script to compute root without subgraph

### ISSUE THREAD

**Issue by julien-devatom** [morpho-org/morpho-optimizers-rewards#18]
## Feature Request

Create a script to compute the distribution off-chain without a given sugraph.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

## Are you willing to resolve this issue by submitting a Pull Request?

- [ ] Yes, I have the time, and I know how to start.
- [ ] Yes, I have the time, but I don't know how to start. I would need guidance.
- [ ] No, I don't have the time, although I believe I could do it if I had the time...
- [ ] No, I don't have the time and I wouldn't even know how to start.

**Comment by ameya-deshmukh** [comment]
@julien-devatom is this still open? Would love to give it a shot :D

**Comment by julien-devatom** [comment]
Hey @ameya-deshmukh, thank you for your enthusiasm. We already have one version internally that is going to be released once needed, but the issue is only in "nice to have" so i don't think that its a good investment for you to do that 😄

**Comment by ameya-deshmukh** [comment]
haha got it, thanks 😄
